### ISSUE TITLE
updating vector-fftw to work with primitive 0.6

### ISSUE THREAD

**Issue by joehealy** [judah/vector-fftw#7]
To use vector-fftw alongside the stackage lts releases, it needs to compile with primitive 0.6.

It appears the change required to do so is relatively simple:

Adding PrimBase to the imports:

import Control.Monad.Primitive (RealWorld,PrimMonad(..),PrimBase(..),
            unsafePrimToPrim, unsafePrimToIO)

and adding primbase to the type signature of executeM:

executeM :: forall m v a b .
        (PrimMonad m, PrimBase m, MVector v a, MVector v b, Storable a, Storable b)
            => Plan a b -- ^ The plan to run.
            -> v (PrimState m) a  -- ^ The input vector.
                    -> v (PrimState m) b -- ^ The output vector.
                    -> m ()

I haven't yet tested this extensively, but it compiles - testing now

**Comment by bgamari** [comment]
This is resolved in 0.1.3.3.
