### ISSUE TITLE
Name of fftw3 dll on windows

### ISSUE THREAD

**Issue by joehealy** [judah/vector-fftw#8]
On windows, the fftw3 dll is called fftw3-3, so the cabal file needs to be modified for vector-fftw to compile. See http://hauptwerk.blogspot.com.au/2013/01/how-to-get-haskell-vector-fftw-package.html for details.

Is it possible to support both windows and unix (maybe with some conditional lines in the .cabal file)?

thanks,

Joe

**Comment by bgamari** [comment]
Fixed.
